server:
  port: 8085
spring:
  profiles:
    active: local
---
spring:
  profiles: local
  data:
    mongodb:
      port: 27017
      host: localhost
      database: transaq
  kafka:
    template:
      default-topic: transaction-events
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      group-id: kafka-consumer-group
      properties:
        specific:
          avro:
            reader: true
        acks: 1
        retries: 10
        schema:
          registry:
            url: http://localhost:8081
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        specific:
          avro:
            reader: true
        acks: 1
        retries: 10
        schema:
          registry:
            url: http://localhost:8081

#    streams:
#      application-id: testing-kafka
#      bootstrap-servers: localhost:9092
#      properties:
#        default:
#          key:
#            serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#          value:
#            serde: org.apache.kafka.common.serialization.Serdes$StringSerde






